name: Backup GitHub Repos to S3

on:
  schedule:
    - cron: '0 2 * * *' # Schedule to run daily at 2 AM
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Clone Repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdir backup
          cd backup
          repos=$(curl -H "Authorization: token $GITHUB_TOKEN" -s https://api.github.com/orgs/${{ github.repository_owner }}/repos | jq -r '.[].clone_url')
          for repo in $repos; do
            git clone $repo
          done

      - name: Compress Repositories
        run: |
          zip -r backup.zip backup

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 cp backup.zip s3://${{ secrets.S3_BUCKET }}/backup_$(date +%Y%m%d%H%M%S).zip
